[package]
name = "zapcode-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1.1", features = ["postgres", "chrono", "uuid", "numeric"] }
diesel-async = { version = "0.4", features = ["postgres", "tokio", "deadpool"] }
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
bigdecimal = { version = "0.4", features = ["serde"] }
privy = "0.10.0"
async-trait = "0.1"
anyhow = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
# starkzap-rs = { version = "0.1.0", features = ["full"] }
starkzap-rs = { path = "/Users/MAC/Rust/starkzap-rs", features = ["full"] }
starknet = "0.17"
base64 = "0.22"
reqwest = { version = "0.12", features = ["json"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "fs"] }
image = "0.25"
qrcode = "0.14"
lettre = { version = "0.11", features = ["tokio1-native-tls"] }
tracing = "0.1"
thiserror = "1.0"
futures = "0.3"
